### ISSUE TITLE
slip/skid not reported correctly in ahrs on oled screen

### ISSUE THREAD

**Issue by gpisapia** [TomBric/stratux-radar-display#16]
Hello, 
I rootcaused this issue: on the ahrs function, the ball stay centrered and seems to net receive the slip/skid value from ahrs.
I didn't push as I didn't create my own branch (yet), here is the fix, the issue is in radar.py, around line 124:
    if ahrs['slipskid'] != round(sit['AHRSSlipSkid']):
--        ahrs['heading'] = round(sit['AHRSSlipSkid'])
++      ahrs['slipskid'] = round(sit['AHRSSlipSkid'])
        ahrs['was_changed'] = True

I am also currently adding gps alti and speed in the small oled. Not very practical after test but can help.

**Comment by TomBric** [comment]
Hi gpisapia,

thanks! Is updated!

Thomas
