### ISSUE TITLE
Case

### ISSUE THREAD

**Issue by mofaheiti** [TomBric/stratux-radar-display#31]
Hi Thomas,
this isn't an issue but i don't know how to communicate on another way.
I've build a New Case to build in a Panel board of a Plane.
Here is the link to the case. https://www.thingiverse.com/thing:4783777
It's made for hard wired Stratux.
- Switch to turn on the display and stratux
- the 3 buttons for the menü
- Bluetooth adapter to connect to an intercom
- Volume poti (to set the volume or to turn the sound off)

Thank you for your work!

Michael

**Comment by mofaheiti** [comment]
If you want, you can use the files and the pictures.
It's a gift from me.

**Comment by TomBric** [comment]
Hi Michael,

thanks for the case design. I will put it into the repo. 
Meanwhile we have several cases designed, I will put the other designs also on the repo in the next days.

I have equipped my cases with LM2596, a very cheap step-down converter. It's working well for the stratux as well as the display. Just put your aircraft power at it, and calibrate the power to 5.1 Volts. Works very well for already a long time in my aircraft. This way you get rid of your usb cables. 

Thomas

**Comment by mofaheiti** [comment]
hi Thomas,
cool!
I will try the lm2596. The stepdowns i tried did a lot of noise in the radio. so i chose the usb cable on a "anker powerdrive" usb charger. It works and have no noise on the radio.

Michael
