### ISSUE TITLE
Full radar screen (circle) on e=paper display 

### ISSUE THREAD

**Issue by Toogo** [TomBric/stratux-radar-display#40]
Now the bottom part of de radar screen is cut of, can't you make it fit (or smaller that it will fit. Now I don't see planes in that part.

Thank you.

Frank

**Comment by TomBric** [comment]
Hi Frank,
I explicitly designed the Epaper-Screen to have a better view in flying direction, because you normally do not care so much about the things behind you. 
Nevertheless it's not a big deal, I can provide an option to have the circle full screen. Just give me some days. 

Thomas

**Comment by TomBric** [comment]
Hi Frank,
an option to show the radar on the Epaper now with full radius is implemented in version 1.3.
You can modify image/stratux_radar.sh, and there add the option  --fullcircle when calling "python3 radar.py  ...."

Thomas
