### ISSUE TITLE
rotary encoder ?

### ISSUE THREAD

**Issue by rudiratlos** [TomBric/stratux-radar-display#56]
are there any plans to use rotary encoder for menu actions, instead of 3 buttons.
For mobile stratux devices, a rotary encoder is easier to mechanical mount it.

e.g. KY-040
turn encoder left/right to select screen (g-meter, ahrs, traffic, log ...)
push encoder button to select specific screen menu (e.g. traffic range...)
turn encoder left/right (on menu sub level)
pish encoder button to selct value

**Comment by TomBric** [comment]
Hi Rudi,
currently no plans. Of course this is feasible. 
We decided for push buttons since this gives more flexibility for mountings and with 3D printed forms these buttons are nicely to be integrated.
