### ISSUE TITLE
GDL 90 or Pilotaware connection

### ISSUE THREAD

**Issue by wadoadi** [TomBric/stratux-radar-display#58]
Hi, this sounds a very interesting project, I have just order the bits to play with…

I fly with Stratux EU normally however, some of the aircraft I fly use Pilotaware, will this work Pilotaware? 

Thanks

**Comment by TomBric** [comment]
Hi wodoadi,
the display connects via the websocket interface to Stratux (like a stratux webclient).
So there is no support for a GDL90 interface.
Thomas

**Comment by wadoadi** [comment]
Ok thanks
