### ISSUE TITLE
Wrong SSID in instructions for OLE image

### ISSUE THREAD

**Issue by wadoadi** [TomBric/stratux-radar-display#59]
In the opening page it gives the connection details as SSID Stratux-Europe, IP 192.168.10.1. however, the connection wasn't made using that SSID. the required SSID for the default connection using the OLE image was stratux  (all lowercase).

Now to add the CO. This is really cool thank you for your work.

**Comment by TomBric** [comment]
I do not know whether I got your comment right. Did you mean in the readme on the github  web page?
I modified the position of the quotation mark. Is that what you commented?

**Comment by wadoadi** [comment]
hi Tom, its probable just how I read the Read.me "Remark: Current configuration is for **Stratux-Europe** on IP address 192.168.10.1. If you have a different configuration please update /home/pi/stratux-radar-display/image/stratux_radar.sh accordingly."

I took the Stratux-Europa before the IP to be the SSID
to make Idot proof maybe add SSID = stratux

**Comment by TomBric** [comment]
Ok, understood and done.

Thomas
