### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by JustDaveIII** [TomBric/stratux-radar-display#66]
Tom, I can't find a way to contact you (including your website that has an unreadable -to me - email address - in the picture ...) , I may be missing someway here ... 

So I want to publicaly say that I am very grateful for the time you took to develope this code. I have it running just fine on my pi zero w2 with the 3.7" display. I started with the 3D printer files for the case and modified it for my needs. 

As a long time freeware / shareware developer I know I am very happy to get feedback from users! So I want to say that I am so appreciative of your work.

After I download the newest version I will follow your "expert" installation instructions to install in on my Stratux unit so that I get all the benifits of Stratux and your efforts. T H A N K    Y O U !!!

**Comment by TomBric** [comment]
Hi,
many thanks, I really appreciate your feedback. I am very happy for every plane with more situational awareness through the radar ..
You can contact me via email and using info as user with the domain name.

Thomas
