### ISSUE TITLE
1.5" oled display issue

### ISSUE THREAD

**Issue by dbr259** [TomBric/stratux-radar-display#74]
Hello Tom, following the instructions you posted, the OLED screen should be installed on the installed stratux, but it does not do so because there are errors from the repositories and the library. My question is ...can you prepare and put it on github. stratux-eu31-with-Oled_1in5-v2.03-d56ca413.img.zip

**Comment by TomBric** [comment]
Done. Unfortunately I do not have an Oled available right now, so I could not check.
Give me a feedback, whether it works.

**Comment by dbr259** [comment]
Strux works, unfortunately not OLED
![stratux](https://github.com/user-attachments/assets/7713f8e3-1548-468e-83d4-26319e8ceee1)
![IMG_1339](https://github.com/user-attachments/assets/9ed91c4f-62f3-4d8c-8f4a-e753a73c3ab0)

**Comment by TomBric** [comment]
Thanks for the offer. I have got enough of the OLEDs available. I just need to built a test system.
I will do that tomorrow.

**Comment by TomBric** [comment]
I uploaded a new version for the Oled in 2.03 release. Its working in my test. Please test yourself as well.
There was an "apt update" missing in the install script.

**Comment by dbr259** [comment]
Its working ..thanks Tom.
