### ISSUE TITLE
Testing the Benewake TFMini Plus Lidar Sensor

### ISSUE THREAD

**Issue by DocTopi** [TomBric/stratux-radar-display#82]
Hi TomBric,

I´ve installed the stratux-radar-display v2.03 on a Zero 2 W with the Oled Display 1.5 inch and Benewake TFMini Plus Lidar Sensor.
Host is Stratux Europe Edition 1.6r1-eu032.

Are there any possibilities for testing the installed Lidar sensor on the table or perhaps during car riding?

Thanks for your recommendations.
Kind regards
Franz

**Comment by TomBric** [comment]
Hi Franz,
you can easily test it on the table:
- Proceed with the long middle button to screen "GPS Distance"
- if the lidar sensor is on (start it with option "-gd") there will be the current distance value displayed. 
Thomas
