### ISSUE TITLE
iOS device as monitor

### ISSUE THREAD

**Issue by DocTopi** [TomBric/stratux-radar-display#84]
Hi Thomas,
the OLED display seems a little bit small, and the ePaper seems a little bit slowly.
Is it possible using an old iOS device as monitor for stratux-radar-display (most of us own an old iPhone and/or iPad)?
Kind regards
Franz

**Comment by TomBric** [comment]
Hi Franz,
sure, that is possible. In fact I implemented the Web-Radar before I decided to implement a special device.
Just use the stratux web frontend and then on the left side select "Radar".
If you then tap on F/S you have it full-screen. Works for IOS and Android.

Thomas
