### ISSUE TITLE
Radar showing "noise" instead of radar

### ISSUE THREAD

**Issue by Stefan-Kosker** [TomBric/stratux-radar-display#87]
I installed the stratux EU32 and radar software afterwards. Today I installed the SDR devices and can see traffic ADS-B in Stratux.

![image](https://github.com/user-attachments/assets/5f9d188d-fa2a-46e8-a157-dc9eda3f866d)

But the screen shows this: 
![image](https://github.com/user-attachments/assets/c6228f71-5cd1-4c54-a672-3fda33de17a2)

What did I wrong? I am using the same screen you suggested and checked the connections again and again. Currently I am still waiting for the T-Beam and GPS Antenna from China. So maybe this is the issue? (No GPS = No Radar)?

Here is my pin-out:

![image](https://github.com/user-attachments/assets/40c42f03-c939-48c1-85bf-0b339c40c5ac)

USB being on the left, 17 is correct position.

Something appears to work at least:
![image](https://github.com/user-attachments/assets/0bd586b7-bc98-4cd6-a268-ac18cb5d61bc)

The manual execution also seems fine:
```
pi@stratux:~/stratux-radar-display/main $ python3 radar.py -r -d Oled_1in5 -c 127.0.0.1
Stratux Radar Display 2.05 running ...
Version: luma.oled 3.10.0 (luma.core 2.4.0)
Display: ssd1351
Interface: spi
Dimensions: 128 x 128
------------------------------------------------------------
```

**Comment by TomBric** [comment]
Cabling seems correct.
Did you **disable** I2C/OGN Transmission under settings?  (see required setting in picture)

![image](https://github.com/user-attachments/assets/49fe32d3-e7aa-4b65-b946-f4040207e486)

**Comment by Stefan-Kosker** [comment]
![IMG_20241126_200301](https://github.com/user-attachments/assets/605f8e61-28f8-4e9e-9bf3-efb08847f594)

Ye. Disabled. Still problem. 

Does it have to be disabled at installation time?

**Comment by TomBric** [comment]
It is ok to disable it and then reboot, not necessary at installation time.
And this does NOT affect T-Beam. It is only needed for a special hardware, a GPIO hat. So no need for an additional pi.

But still your problem exists. I will check with my hardware in the next days. Strange ...

**Comment by Stefan-Kosker** [comment]
Appreciate it. I would really like to not having to buy another end device. Because my next step will be classic over engineered German solution with a mini pc, hdmi touch screen and shit. Then I can throw away the whole energy planning with 30Ah powerbank out of window...

Thank you mate.

**Comment by Stefan-Kosker** [comment]
Ye Display works.

**Comment by TomBric** [comment]
Hi Stefan, I just checked with my hardware and the oled display:
- Installed stratux 032 on a raspberry pi 3B
- stratux connected to my home network and persistent logging on
- started and stopped timesync to get proper time (gps was not yet available)
- sudo apt update  (install git did not work the first time)
- sudo apt install git
- git clone https://github.com/TomBric/stratux-radar-display.git
- sudo /bin/bash /home/pi/stratux-radar-display/image/configure_radar_on_stratux.sh
- checked image/stratux_radar.sh: oled was already configured
- rebooted
- Radar 2.05 is working
Can you please retry a full installation? Maybe you received outdated libraries due to missing proper time.
Thomas

**Comment by Stefan-Kosker** [comment]
Checklist:

- Flashed stratux-v1.6r1-eu032-ff1f01dc.img into a sandisk32gb microSSD
- Stratux connected to my home network and tested for functionality:
![image](https://github.com/user-attachments/assets/fd8848d1-c4a6-4fc7-bb14-f55e3af55329)

- persistent logging on, OGN Transmission via I2c off:
![image](https://github.com/user-attachments/assets/094704d5-f647-484e-b0f7-d511817e62fc)

- started and stopped timesync to get proper time (gps was not yet available)
![image](https://github.com/user-attachments/assets/8a52626a-5b97-432b-a020-1d7ffb1ffd0d)

- sudo apt update (as suggested in the PR)
![image](https://github.com/user-attachments/assets/09c1c8d2-37c7-4e77-aaab-aff231b74113)

- sudo apt install git: Done
- git clone https://github.com/TomBric/stratux-radar-display.git
![image](https://github.com/user-attachments/assets/3a96243c-4c5c-46d9-975c-45a023f4f4cf)

- sudo /bin/bash /home/pi/stratux-radar-display/image/configure_radar_on_stratux.sh
![image](https://github.com/user-attachments/assets/8df619a7-dcec-44c3-bab3-8b686f2fff15)

- checked image/stratux_radar.sh: oled was already configured
![image](https://github.com/user-attachments/assets/e1ecd879-bea8-4852-8c25-a31dcd05e7bb)

- rebooted
Power off and on

Result: Still failing.

I will send raspberry and the screen back and purchase a new one. Maybe it is a hardware fail. Theoretically, when I push SD Card into the new Raspberry, it should work out without any issues.

**Comment by TomBric** [comment]
I am still considering a cabling or software problem.
Before you send everything back, maybe you can do a test with luma, which is the oled software.
See examples and instructions here:
github.com/rm-hull/luma.examples
This way you can test display and pi together independent of stratux.

**Comment by Stefan-Kosker** [comment]
Yeah no, so the luma.examples I couldn't run. Waveshare test just stays black. Sad

**Comment by TomBric** [comment]
I am actually using a pi 3B v1.2.
Same as yours.
But also with a Pi4 it works.

**Comment by Stefan-Kosker** [comment]
Allright. Then lets do it easier. Is a HAT possible? I already ordered a new 3b+ and would also order this one:
https://amzn.eu/d/hlwbcrM

Any experience with HAT 3.7inch? Has 3way and 4way spi, I will not use the buttons. This way I shouldn't have any problems with wrong cabling etc. Just place it on the rasp pi and 3d print a proper box with that.

What do you think?

**Comment by TomBric** [comment]
The hat is possible, it works on additional pi zero and also with a pi3b.
The problem with the hat is that you are not able to connect additional devices like baro and ahrs to stratux.
So in your case it is not a proper solution.
BTW: Did you also try the full image I provide with stratux and oled from github, see here
`https://github.com/TomBric/stratux-radar-display/releases/download/v2.05/stratux-eu032-with-Oled_1in5-v2.05-00e2d1ef.img.zip`

**Comment by Stefan-Kosker** [comment]
Will try it later, currently I am driving for a nice flight :)

Since I am going to use t beam, baro is going to be on Io of tbeam i2c. According to viruspilot his docs, this should work.

**Comment by TomBric** [comment]
Baro on T-Beam is possible, but AHRS not.
Have fun on your flight. I also wanted to fly this morning, but Koblenz was still foggy.

**Comment by Stefan-Kosker** [comment]
> The hat is possible, it works on additional pi zero and also with a pi3b. The problem with the hat is that you are not able to connect additional devices like baro and ahrs to stratux. So in your case it is not a proper solution. BTW: Did you also try the full image I provide with stratux and oled from github, see here `https://github.com/TomBric/stratux-radar-display/releases/download/v2.05/stratux-eu032-with-Oled_1in5-v2.05-00e2d1ef.img.zip`

![image](https://github.com/user-attachments/assets/4432263c-8e14-42e3-bdb4-9e45f93712ff)

Sad but no chance

**Comment by TomBric** [comment]
I just looked at your picture: You are using a different OLED Module!
Software is made for waveshare 14747, which is an RGB module. Somehow your module looks different compared to mine.
Please check your order. It has to be set to 4-SPI.
[https://www.waveshare.com/1.5inch-rgb-oled-module.htm](url)

**Comment by Stefan-Kosker** [comment]
E-Paper Hat works flawlessly. Tells me even noGPS. Thank you

**Comment by TomBric** [comment]
Good to hear!
